// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Face":return img`
............aaaaa...
.......aaaaaaaaaa...
......aa333333333...
....aaa333ddddddd...
....a3333dddddddd...
...aa3333dddddddd...
...a333dddddddddd...
..aa33ddddddddddd...
..a33dddddddddddd...
..a33dddddddddddd...
..a33dddddddddddd...
.....dddddddddddd...
.....dddddddddddd...
.....dddddddddddd...
....................
....................
....................
....................
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
